development:
  adapter: mysql2
  database: pathfinder_development
  host: 127.0.0.1
  pool: 5
  socket: /tmp/mysql.sock
  timeout: 5000
  username: root
  password:

test:
  adapter: mysql2
  database: pathfinder_test
  host: 127.0.0.1
  pool: 5
  socket: /tmp/mysql.sock
  timeout: 5000
  username: root
  password:

production:
  adapter: mysql2
  database: pathfinder_production
  host: 127.0.0.1
  pool: 5
  socket: /tmp/mysql.sock
  timeout: 5000
  username: root
  password:

